### ISSUE TITLE
how to get the 0x6c28e8 and 0x300000

### ISSUE THREAD

**Issue by J-shiro** [bash-c/pwn_repo#5]
`io.sendlineafter("stackoverflow: ", str(0x6c28e8)) # lsb(_IO_2_1_stdin_.file._IO_buf_base_) = \x00`
`io.sendlineafter("stackoverflow: ", str(0x300000))`
**in the whctf2017 stackoverflow**
Hello, I would like to ask, I use different sizes to get libc addresses and individual addresses. But in the end the problem can not be solved, so I feel that the problem may be on the size, how is the **size:0x6c28e8, 0x300000** in these two lines of code obtained?

**Comment by bash-c** [comment]
Hi there,

It's such a long time since I wrote this code. Honestly, I can't remember what the two numbers are.
It seems like there are many writeups for this challenge. Hope this can help you.
![image](https://user-images.githubusercontent.com/24247697/197698561-93edcc52-0669-48d0-bf06-abeb2853e812.png)

**Comment by J-shiro** [comment]
> Hi there,
> 
> It's such a long time since I wrote this code. Honestly, I can't remember what the two numbers are. It seems like there are many writeups for this challenge. Hope this can help you. ![image](https://user-images.githubusercontent.com/24247697/197698561-93edcc52-0669-48d0-bf06-abeb2853e812.png)

Thanks! I read some writeups these days and got a rough idea.
